export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav style={{display: 'flex', gap: 24, marginBottom: 24}}>
          <a href="/">Client</a>
          <a href="/server">Server</a>
          <a href="/route-handler">Route handler</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
